export const API_PROJECT_NAME='mydomi'

export const COLOR_PRIMARY='#6979F8'

export const ACTION_USUARIO_ACCEDIENDO='ACTION_USUARIO_ACCEDIENDO'
export const ACTION_USUARIO_ACCESO_CORRECTO='ACTION_USUARIO_ACCESO_CORRECTO'
export const ACTION_USUARIO_ERROR_ACCEDIENDO='ACTION_USUARIO_ERROR_ACCEDIENDO'

export const NEGOCIO_CARGANDO='NEGOCIO_CARGANDO'
export const NEGOCIO_CARGADO='NEGOCIO_CARGADO'
export const NEGOCIO_ERROR_CARGANDO='NEGOCIO_ERROR_CARGANDO'