export const API_PROJECT_NAME = 'mydomi';

export const COLOR_BG = '#F7F8F9';
export const COLOR_PRIMARY = '#733189';
export const COLOR_ACCENT = '#EA8915';
export const COLOR_TEXT = '#959396';
export const COLOR_BG_TAPBAR = '#e5e5e5';
export const COLOR_DESATIVADO = '#a0a0a0';

export const ACTION_USUARIO_ACCEDIENDO = 'ACTION_USUARIO_ACCEDIENDO';
export const ACTION_USUARIO_ACCESO_CORRECTO = 'ACTION_USUARIO_ACCESO_CORRECTO';
export const ACTION_USUARIO_ERROR_ACCEDIENDO =
  'ACTION_USUARIO_ERROR_ACCEDIENDO';

export const NEGOCIO_CARGANDO = 'NEGOCIO_CARGANDO';
export const NEGOCIO_CARGADO = 'NEGOCIO_CARGADO';
export const NEGOCIO_ERROR_CARGANDO = 'NEGOCIO_ERROR_CARGANDO';

export const CARRITO_CARGANDO = 'CARRITO_CARGANDO';
export const CARRITO_CARGADO = 'CARRITO_CARGADO';
export const CARRITO_BORRAR_PRODUCTO = 'CARRITO_BORRAR_PRODUCTO';
export const CARRITO_SET_CANTIDAD_PRODUCTO = 'CARRITO_SET_CANTIDAD_PRODUCTO';
export const CARRITO_SET_INSTRUCCIONES_PRODUCTO =
  'CARRITO_SET_INSTRUCCIONES_PRODUCTO';
